package edu.cmu.policymanager.DataRepository.memory;

import android.Manifest;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by Mike Czapik (Carnegie Mellon University) on 5/30/2018.
 */

public class MemoryDataStore {
    public MemoryDataStore() {}

    public static final String[][] PURPOSE_CATEGORIES = {
            {"WEATHER", "App Features"},
            {"INTERNAL", "App Internals"},
            {"GEOTAGGING", "App Features"},
            {"TARGETED_ADS", "Monetization"},
            {"SOCIAL", "App Features"},
            {"NAVIGATION", "App Features"},
            {"NEARBY-PLACES", "App Features"},
            {"MOBILE_ANALYTICS", "Data Sharing"},
            {"UTILITY", "App Internals"},
            {"SNS", "Data Sharing"},
            {"UNKNOWN", "Other"},
            {"PAYMENT", "Monetization"},
            {"EMERGENCY", "App Features"},
            {"SEARCH_ENGINE", "App Features"},
            {"DEVELOPMENT_AID", "App Internals"},
            {"CONTENT_PROVIDER", "Data Sharing"},
            {"GAME_ENGINE", "App Internals"}
    };

    public static Map<String, String[]> permissionPurposeMap = new HashMap<String, String[]>() {{
        put("android.permission.ACCESS_CHECKIN_PROPERTIES", new String[]                    {"SOCIAL", "SEARCH_ENGINE"});
        put("android.permission.ACCESS_COARSE_LOCATION", new String[]                       {"WEATHER", "SOCIAL", "SEARCH_ENGINE"});
        put("android.permission.ACCESS_FINE_LOCATION", new String[]                         {"NAVIGATION", "EMERGENCY", "GEOTAGGING", "NEARBY-PLACES"});
        put("android.permission.ACCESS_PRIVATE_LOCATION", new String[]                      {"UTILITY", "INTERNAL", "EMERGENCY", "CONTENT_PROVIDER"});
        put("android.permission.ACCESS_MOCK_LOCATION", new String[]                         {"DEVELOPMENT_AID"});
        put("android.permission.ACCESS_MTP", new String[]                                   {"GEOTAGGING", "DEVELOPMENT_AID", "CONTENT_PROVIDER", "GAME_ENGINE"});
        put("android.permission.ACCESS_NOTIFICATIONS", new String[]                         {"SOCIAL", "PAYMENT", "TARGETED_ADS"});
        put("android.permission.ACCESS_SURFACE_FLINGER", new String[]                       {"GAME_ENGINE", "DEVELOPMENT_AID"});
        put("android.permission.ACCESS_VOICE_INTERACTION_SERVICE", new String[]             {"UTILITY", "MOBILE_ANALYTICS", "SOCIAL"});
        put("android.permission.ACCOUNT_MANAGER", new String[]                              {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.ASEC_ACCESS", new String[]                                  {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.ASEC_CREATE", new String[]                                  {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.ASEC_DESTROY", new String[]                                 {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.ASEC_MOUNT_UNMOUNT", new String[]                           {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.ASEC_RENAME", new String[]                                  {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.AUTHENTICATE_ACCOUNTS", new String[]                        {"UTILITY", "INTERNAL"});
        put("android.permission.BACKUP", new String[]                                       {"INTERNAL", "UTILITY"});
        put("android.permission.BIND_APPWIDGET", new String[]                               {"UNKNOWN"});
        put("android.permission.BLUETOOTH", new String[]                                    {"PAYMENT", "GAME_ENGINE", "INTERNAL", "NAVIGATION"});
        put("android.permission.BLUETOOTH_ADMIN", new String[]                              {"INTERNAL", "DEVELOPMENT_AID"});
        put("android.permission.BLUETOOTH_MAP", new String[]                                {"NAVIGATION", "SEARCH_ENGINE", "INTERNAL"});
        put("android.permission.BLUETOOTH_PRIVILEGED", new String[]                         {"INTERNAL"});
        put("android.permission.BLUETOOTH_STACK", new String[]                              {"INTERNAL", "DEVELOPMENT_AID"});
        put("android.permission.BRICK", new String[]                                        {"INTERNAL"});
        put("android.permission.BROADCAST_CALLLOG_INFO", new String[]                       {"INTERNAL"});
        put("android.permission.BROADCAST_NETWORK_PRIVILEGED", new String[]                 {"INTERNAL"});
        put("android.permission.BROADCAST_PACKAGE_REMOVED", new String[]                    {"INTERNAL"});
        put("android.permission.BROADCAST_PHONE_ACCOUNT_REGISTRATION", new String[]         {"INTERNAL"});
        put("android.permission.BROADCAST_SMS", new String[]                                {"INTERNAL"});
        put("android.permission.BROADCAST_WAP_PUSH", new String[]                           {"UTILITY"});
        put("android.permission.CALL_PRIVILEGED", new String[]                              {"SOCIAL", "PAYMENT"});
        put("android.permission.CAPTURE_AUDIO_HOTWORD", new String[]                        {"GAME_ENGINE", "SEARCH_ENGINE", "UTILITY", "INTERNAL"});
        put("android.permission.CAPTURE_AUDIO_OUTPUT", new String[]                         {"GAME_ENGINE", "SEARCH_ENGINE", "UTILITY", "INTERNAL"});
        put("android.permission.CAPTURE_SECURE_VIDEO_OUTPUT", new String[]                  {"GAME_ENGINE", "SEARCH_ENGINE", "UTILITY", "INTERNAL"});
        put("android.permission.CAPTURE_VIDEO_OUTPUT", new String[]                         {"GAME_ENGINE", "SEARCH_ENGINE", "UTILITY", "INTERNAL"});
        put("android.permission.CARRIER_FILTER_SMS", new String[]                           {"SNS", "SEARCH_ENGINE", "UTILITY", "INTERNAL"});
        put("android.permission.CHANGE_COMPONENT_ENABLED_STATE", new String[]               {"UTILITY", "INTERNAL"});
        put("android.permission.CHANGE_NETWORK_STATE", new String[]                         {"SEARCH_ENGINE", "UTILITY", "INTERNAL"});
        put("android.permission.CHANGE_WIFI_MULTICAST_STATE", new String[]                  {"CONTENT_PROVIDER", "UTILITY"});
        put("android.permission.CHANGE_WIFI_STATE", new String[]                            {"CONTENT_PROVIDER", "UTILITY"});
        put("android.permission.CHANGE_WIMAX_STATE", new String[]                           {"INTERNAL", "UTILITY"});
        put("android.permission.CONFIGURE_WIFI_DISPLAY", new String[]                       {"CONTENT_PROVIDER", "UTILITY"});
        put("android.permission.CONTROL_KEYGUARD", new String[]                             {"UNKNOWN"});
        put("android.permission.CONTROL_LOCATION_UPDATES", new String[]                     {"UNKNOWN"});
        put("android.permission.CONTROL_VPN", new String[]                                  {"UNKNOWN"});
        put("android.permission.COPY_PROTECTED_DATA", new String[]                          {"UNKNOWN"});
        put("android.permission.CRYPT_KEEPER", new String[]                                 {"UNKNOWN"});
        put("android.permission.DELETE_PACKAGES", new String[]                              {"UNKNOWN"});
        put("android.permission.DISPATCH_NFC_MESSAGE", new String[]                         {"UNKNOWN"});
        put("android.permission.FACTORY_TEST", new String[]                                 {"UNKNOWN"});
        put("android.permission.FORCE_STOP_PACKAGES", new String[]                          {"UNKNOWN"});
        put("android.permission.GET_ACCOUNTS_PRIVILEGED", new String[]                      {"UNKNOWN"});
        put("android.permission.GET_PACKAGE_SIZE", new String[]                             {"UNKNOWN"});
        put("android.permission.GET_TASKS", new String[]                                    {"UNKNOWN"});
        put("android.permission.GET_TOP_ACTIVITY_INFO", new String[]                        {"UNKNOWN"});
        put("android.permission.GLOBAL_SEARCH", new String[]                                {"UNKNOWN"});
        put("android.permission.GRANT_RUNTIME_PERMISSIONS", new String[]                    {"UNKNOWN"});
        put("android.permission.INJECT_EVENTS", new String[]                                {"UNKNOWN"});
        put("android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS", new String[]            {"UNKNOWN"});
        put("android.permission.INSTALL_LOCATION_PROVIDER", new String[]                    {"UNKNOWN"});
        put("android.permission.INSTALL_PACKAGES", new String[]                             {"UNKNOWN"});
        put("android.permission.INTENT_FILTER_VERIFICATION_AGENT", new String[]             {"UNKNOWN"});
        put("android.permission.INTERACT_ACROSS_USERS", new String[]                        {"UNKNOWN"});
        put("android.permission.INTERACT_ACROSS_USERS_FULL", new String[]                   {"UNKNOWN"});
        put("android.permission.INTERNAL_SYSTEM_WINDOW", new String[]                       {"UNKNOWN"});
        put("android.permission.KILL_BACKGROUND_PROCESSES", new String[]                    {"UNKNOWN"});
        put("android.permission.KILL_UID", new String[]                                     {"UNKNOWN"});
        put("android.permission.LOCAL_MAC_ADDRESS", new String[]                            {"UTILITY"});
        put("android.permission.LOCATION_HARDWARE", new String[]                            {"UTILITY"});
        put("android.permission.MANAGE_ACCOUNTS", new String[]                              {"UTILITY"});
        put("android.permission.MANAGE_APP_TOKENS", new String[]                            {"UTILITY"});
        put("android.permission.MANAGE_CA_CERTIFICATES", new String[]                       {"UTILITY"});
        put("android.permission.MANAGE_DEVICE_ADMINS", new String[]                         {"UTILITY"});
        put("android.permission.MANAGE_DOCUMENTS", new String[]                             {"UTILITY"});
        put("android.permission.MANAGE_FINGERPRINT", new String[]                           {"UTILITY"});
        put("android.permission.MANAGE_MEDIA_PROJECTION", new String[]                      {"UTILITY"});
        put("android.permission.MANAGE_NETWORK_POLICY", new String[]                        {"UTILITY"});
        put("android.permission.MANAGE_PROFILE_AND_DEVICE_OWNERS", new String[]             {"UTILITY"});
        put("android.permission.MANAGE_USB", new String[]                                   {"UTILITY"});
        put("android.permission.MANAGE_USERS", new String[]                                 {"UTILITY"});
        put("android.permission.MANAGE_VOICE_KEYPHRASES", new String[]                      {"UTILITY"});
        put("android.permission.MASTER_CLEAR", new String[]                                 {"UTILITY"});
        put("android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS", new String[]            {"UTILITY"});
        put("android.permission.MODIFY_AUDIO_ROUTING", new String[]                         {"UTILITY"});
        put("android.permission.MODIFY_PARENTAL_CONTROLS", new String[]                     {"UTILITY"});
        put("android.permission.MODIFY_PHONE_STATE", new String[]                           {"UTILITY"});
        put("android.permission.MOUNT_FORMAT_FILESYSTEMS", new String[]                     {"UTILITY"});
        put("android.permission.MOUNT_UNMOUNT_FILESYSTEMS", new String[]                    {"UTILITY"});
        put("android.permission.MOVE_PACKAGE", new String[]                                 {"UTILITY"});
        put("android.permission.NET_ADMIN", new String[]                                    {"UTILITY"});
        put("android.permission.NET_TUNNELING", new String[]                                {"UTILITY"});
        put("android.permission.NFC", new String[]                                          {"PAYMENT", "SOCIAL", "GAME_ENGINE"});
        put("android.permission.NFC_HANDOVER_STATUS", new String[]                          {"UTILITY"});
        put("android.permission.NOTIFY_PENDING_SYSTEM_UPDATE", new String[]                 {"UTILITY"});
        put("android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS", new String[]             {"UTILITY"});
        put("android.permission.OVERRIDE_WIFI_CONFIG", new String[]                         {"UTILITY"});
        put("android.permission.PACKAGE_PRIVACY_VERIFICATION_AGENT", new String[]           {"UTILITY"});
        put("android.permission.PACKAGE_USAGE_STATS", new String[]                          {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.PACKAGE_VERIFICATION_AGENT", new String[]                   {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.PEERS_MAC_ADDRESS", new String[]                            {"UTILITY"});
        put("android.permission.PERFORM_CDMA_PROVISIONING", new String[]                    {"UTILITY"});
        put("android.permission.PERFORM_SIM_ACTIVATION", new String[]                       {"UTILITY"});
        put("android.permission.POLICY_MANAGER_SERVICE", new String[]                       {"UTILITY"});
        put("android.permission.PROCESS_CALLLOG_INFO", new String[]                         {"UTILITY"});
        put("android.permission.PROCESS_PHONE_ACCOUNT_REGISTRATION", new String[]           {"UTILITY"});
        put("android.permission.PROVIDE_TRUST_AGENT", new String[]                          {"UTILITY"});
        put("android.permission.READ_INPUT_STATE", new String[]                             {"GAME_ENGINE"});
        put("android.permission.READ_INSTALL_SESSIONS", new String[]                        {"UTILITY"});
        put("android.permission.READ_LOGS", new String[]                                    {"UTILITY"});
        put("android.permission.READ_NETWORK_USAGE_HISTORY", new String[]                   {"GAME_ENGINE"});
        put("android.permission.READ_PRECISE_PHONE_STATE", new String[]                     {"GAME_ENGINE"});
        put("android.permission.READ_PRIVILEGED_PHONE_STATE", new String[]                  {"GAME_ENGINE"});
        put("android.permission.READ_PROFILE", new String[]                                 {"GAME_ENGINE"});
        put("android.permission.READ_SEARCH_INDEXABLES", new String[]                       {"GAME_ENGINE"});
        put("android.permission.READ_SOCIAL_STREAM", new String[]                           {"SOCIAL", "SNS"});
        put("android.permission.READ_SYNC_SETTINGS", new String[]                           {"UTILITY"});
        put("android.permission.READ_SYNC_STATS", new String[]                              {"UTILITY"});
        put("android.permission.READ_USER_DICTIONARY", new String[]                         {"SOCIAL", "UTILITY", "INTERNAL", "DEVELOPMENT_AID"});
        put("android.permission.READ_WIFI_CREDENTIAL", new String[]                         {"UTILITY", "DEVELOPMENT_AID"});
        put("android.permission.READ_CONTACTS", new String[]                                {"GAME_ENGINE"});
        put("android.permission.READ_EXTERNAL_STORAGE", new String[]                        {"GAME_ENGINE"});
        put("android.permission.READ_PHONE_STATE", new String[]                             {"GAME_ENGINE"});
        put("android.permission.READ_SMS", new String[]                                     {"SOCIAL", "SNS", "TARGETED_ADS", "EMERGENCY"});
        put("android.permission.RECEIVE_MMS", new String[]                                  {"SOCIAL", "SNS", "TARGETED_ADS", "EMERGENCY"});
        put("android.permission.RECEIVE_SMS", new String[]                                  {"SOCIAL", "SNS", "TARGETED_ADS", "EMERGENCY"});
        put("android.permission.RECORD_AUDIO", new String[]                                 {"SOCIAL", "SNS", "TARGETED_ADS", "EMERGENCY"});
        put("android.permission.REGISTER_CALL_PROVIDER", new String[]                       {"GAME_ENGINE", "UNKNOWN"});
        put("android.permission.REGISTER_CONNECTION_MANAGER", new String[]                  {"UTILITY"});
        put("android.permission.REGISTER_SIM_SUBSCRIPTION", new String[]                    {"UTILITY"});
        put("android.permission.REORDER_TASKS", new String[]                                {"UTILITY"});
        put("android.permission.REPORT_SUPERUSER", new String[]                             {"UTILITY"});
        put("android.permission.REQUEST_SUPERUSER", new String[]                            {"UTILITY"});
        put("android.permission.RESET_FINGERPRINT_LOCKOUT", new String[]                    {"UTILITY"});
        put("android.permission.RESTART_PACKAGES", new String[]                             {"UTILITY"});
        put("android.permission.RETRIEVE_WINDOW_CONTENT", new String[]                      {"UTILITY"});
        put("android.permission.RETRIEVE_WINDOW_TOKEN", new String[]                        {"UTILITY"});
        put("android.permission.REVOKE_RUNTIME_PERMISSIONS", new String[]                   {"UTILITY"});
        put("android.permission.SEND_CALL_LOG_CHANGE", new String[]                         {"UTILITY"});
        put("android.permission.SEND_DOWNLOAD_COMPLETED_INTENTS", new String[]              {"UTILITY"});
        put("android.permission.SEND_RESPOND_VIA_MESSAGE", new String[]                     {"UTILITY"});
        put("android.permission.SEND_SMS", new String[]                                     {"SOCIAL", "SNS", "PAYMENT"});
        put("android.permission.SERIAL_PORT", new String[]                                  {"DEVELOPMENT_AID", "UTILITY"});
        put("android.permission.SET_ACTIVITY_WATCHER", new String[]                         {"UTILITY"});
        put("android.permission.SET_ALWAYS_FINISH", new String[]                            {"UTILITY"});
        put("android.permission.SET_ANIMATION_SCALE", new String[]                          {"UTILITY"});
        put("android.permission.SET_DEBUG_APP", new String[]                                {"UTILITY"});
        put("android.permission.SET_INPUT_CALIBRATION", new String[]                        {"UTILITY"});
        put("android.permission.SET_ORIENTATION", new String[]                              {"UTILITY"});
        put("android.permission.SET_POINTER_SPEED", new String[]                            {"UTILITY"});
        put("android.permission.SET_PREFERRED_APPLICATIONS", new String[]                   {"UTILITY"});
        put("android.permission.SET_PROCESS_LIMIT", new String[]                            {"UTILITY"});
        put("android.permission.SET_SCREEN_COMPATIBILITY", new String[]                     {"UTILITY"});
        put("android.permission.SET_TIME", new String[]                                     {"UTILITY"});
        put("android.permission.SET_TIME_ZONE", new String[]                                {"UTILITY"});
        put("android.permission.STATUS_BAR", new String[]                                   {"UTILITY"});
        put("android.permission.STATUS_BAR_SERVICE", new String[]                           {"UTILITY"});
        put("android.permission.STOP_APP_SWITCHES", new String[]                            {"UTILITY"});
        put("android.permission.SUBSCRIBED_FEEDS_READ", new String[]                        {"UTILITY"});
        put("android.permission.SUBSCRIBED_FEEDS_WRITE", new String[]                       {"UTILITY"});
        put("android.permission.TEMPORARY_ENABLE_ACCESSIBILITY", new String[]               {"UTILITY"});
        put("android.permission.TRANSMIT_IR", new String[]                                  {"UTILITY"});
        put("android.permission.TRUST_LISTENER", new String[]                               {"UTILITY"});
        put("android.permission.UPDATE_APP_OPS_STATS", new String[]                         {"UTILITY"});
        put("android.permission.UPDATE_CONFIG", new String[]                                {"UTILITY"});
        put("android.permission.UPDATE_DEVICE_STATS", new String[]                          {"UTILITY"});
        put("android.permission.UPDATE_LOCK", new String[]                                  {"UTILITY"});
        put("android.permission.USE_CREDENTIALS", new String[]                              {"UTILITY"});
        put("android.permission.WRITE_APN_SETTINGS", new String[]                           {"UTILITY"});
        put("android.permission.WRITE_DREAM_STATE", new String[]                            {"UTILITY"});
        put("android.permission.WRITE_GSERVICES", new String[]                              {"UTILITY"});
        put("android.permission.WRITE_MEDIA_STORAGE", new String[]                          {"TARGETED_ADS", "EMERGENCY", "SOCIAL", "WEATHER"});
        put("android.permission.WRITE_PROFILE", new String[]                                {"UTILITY", "SOCIAL", "GAME_ENGINE"});
        put("android.permission.WRITE_SECURE_SETTINGS", new String[]                        {"UTILITY", "INTERNAL"});
        put("android.permission.WRITE_SETTINGS", new String[]                               {"UTILITY", "EMERGENCY"});
        put("android.permission.WRITE_SMS", new String[]                                    {"SOCIAL", "UTILITY"});
        put("android.permission.WRITE_SOCIAL_STREAM", new String[]                          {"SOCIAL", "UTILITY"});
        put("android.permission.WRITE_SYNC_SETTINGS", new String[]                          {"DEVELOPMENT_AID", "UTILITY"});
        put("android.permission.WRITE_USER_DICTIONARY", new String[]                        {"UTILITY"});
        put("android.permission.WRITE_CONTACTS", new String[]                               {"UTILITY"});
        put("android.permission.WRITE_EXTERNAL_STORAGE", new String[]                       {"UTILITY"});
        put("com.android.browser.permission.READ_HISTORY_BOOKMARKS", new String[]           {"INTERNAL"});
        put("com.android.browser.perMission.write_history_bookmarks", new String[]          {"INTERNAL"});
        put("com.android.certinstaller.INSTall_as_user", new String[]                       {"INTERNAL"});
        put("com.android.email.perMission.access_provider", new String[]                    {"INTERNAL"});
        put("com.android.launcher.perMission.install_shortcut", new String[]                {"INTERNAL"});
        put("com.android.launcher.permission.UNINSTALL_SHORTCUT", new String[]              {"INTERNAL"});
        put("com.android.launcher3.perMission.receive_first_load_broadcast", new String[]   {"INTERNAL"});
        put("com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS", new String[]      {"INTERNAL"});
        put("com.android.printspooler.permission.ACCESS_ALL_PRINT_JOBS", new String[]       {"INTERNAL"});
        put("com.android.voicemail.permission.READ_VOICEMAIL", new String[]                 {"INTERNAL", "CONTENT_PROVIDER"});
        put("com.android.voicemail.perMission.write_voicemail", new String[]                {"INTERNAL", "SOCIAL"});
    }};

    public static Map<String, String[]> permissionMap = new HashMap<String, String[]>() {{
        put(Manifest.permission.READ_CALENDAR, new String[]                                 {"Read Calendar",                            "2", ""});
        put(Manifest.permission.WRITE_CALENDAR, new String[]                                {"Write Calendar",                           "2", ""});
        put("android.permission.READ_CALL_LOG", new String[]                                {"Read Call Logs",                           "2", ""});
        put("android.permission.WRITE_CALL_LOG", new String[]                               {"Write Call Logs",                          "2", ""});
        put("android.permission.READ_PHONE_NUMBERS", new String[]                           {"Read Phone Numbers",                       "2", ""});
        put("android.permission.CALL_PHONE", new String[]                                   {"Initiate Phone Call",                      "2", ""});
        put("android.permission.ANSWER_PHONE_CALLS", new String[]                           {"Answer Phone Calls",                       "2", ""});
        put(Manifest.permission.ADD_VOICEMAIL, new String[]                                 {"Add Voicemail",                            "2", ""});
        put(Manifest.permission.PROCESS_OUTGOING_CALLS, new String[]                        {"Process Outgoing Calls",                   "2", ""});
        put("android.permission.USE_SIP", new String[]                                      {"Use Free VoIP",                            "2", ""});
        put("android.permission.BODY_SENSORS", new String[]                                 {"Use Body Sensors",                         "2", ""});
        put("android.permission.RECEIVE_WAP_PUSH", new String[]                             {"Receive WAP Push",                         "2", ""});
        put("android.intent.category.MASTER_CLEAR.permission.C2D_MESSAGE", new String[]     {"C2D Message",                              "0", ""});
        put("android.permission.ACCESS_ALL_DOWNLOADS", new String[]                         {"Access Downloads",                         "1", ""});
        put("android.permission.ACCESS_CACHE_FILESYSTEM", new String[]                      {"Cache Filesystem",                         "1", ""});
        put("android.permission.ACCESS_CHECKIN_PROPERTIES", new String[]                    {"Checkin Properties",                       "2", "Storage/Filesystem"});
        put("android.permission.ACCESS_CONTENT_PROVIDERS_EXTERNALLY", new String[]          {"Access Content Providers Externally",      "1", ""});
        put("android.permission.ACCESS_DOWNLOAD_MANAGER", new String[]                      {"Access Download Manager",                  "1", ""});
        put("android.permission.ACCESS_DOWNLOAD_MANAGER_ADVANCED", new String[]             {"Download Manager Advanced",                "1", ""});
        put("android.permission.ACCESS_DRM_CERTIFICATES", new String[]                      {"DRM Certificates",                         "1", ""});
        put("android.permission.ACCESS_COARSE_LOCATION", new String[]                       {"Coarse Location",                          "2", "Location"});
        put("android.permission.ACCESS_FINE_LOCATION", new String[]                         {"Fine Location",                            "2", "Location"});
        put("android.permission.ACCESS_PRIVATE_LOCATION", new String[]                      {"Private Location",                         "0", ""});
        put("android.permission.ACCESS_FM_RADIO", new String[]                              {"FM Radio",                                 "0", ""});
        put("android.permission.ACCESS_INPUT_FLINGER", new String[]                         {"Input Flinger",                            "0", ""});
        put("android.permission.ACCESS_KEYGUARD_SECURE_STORAGE", new String[]               {"Access Keyguard Secure Storage",           "1", ""});
        put("android.permission.ACCESS_LOCATION_EXTRA_COMMANDS", new String[]               {"Access Location Extra Commands",           "1", ""});
        put("android.permission.ACCESS_MOCK_LOCATION", new String[]                         {"Mock Location",                            "0", ""});
        put("android.permission.ACCESS_MTP", new String[]                                   {"Access MTP",                               "2", ""});
        put("android.permission.ACCESS_NETWORK_CONDITIONS", new String[]                    {"Network Conditions",                       "1", ""});
        put("android.permission.ACCESS_NETWORK_STATE", new String[]                         {"Network State",                            "1", ""});
        put("android.permission.ACCESS_NOTIFICATION_POLICY", new String[]                   {"Access Notification Policy",               "1", ""});
        put("android.permission.ACCESS_NOTIFICATIONS", new String[]                         {"Notifications",                            "2", "Android/Apps"});
        put("android.permission.ACCESS_PDB_STATE", new String[]                             {"PDB State",                                "0", ""});
        put("android.permission.ACCESS_SURFACE_FLINGER", new String[]                       {"Surface Flinger",                          "2", ""});
        put("android.permission.BIND_VOICE_INTERACTION", new String[]                       {"Voice Interaction Service",                "2", ""});
        put("android.permission.ACCESS_WIFI_STATE", new String[]                            {"Wifi State",                               "1", ""});
        put("android.permission.ACCESS_WIMAX_STATE", new String[]                           {"WiMax State",                              "1", ""});
        put("android.permission.ACCOUNT_MANAGER", new String[]                              {"Account Manager",                          "2", ""});
        put("android.permission.ALLOW_ANY_CODEC_FOR_PLAYBACK", new String[]                 {"Allow Any Codec For Playback",             "0", ""});
        put("android.permission.ASEC_ACCESS", new String[]                                  {"ASEC Access",                              "2", ""});
        put("android.permission.ASEC_CREATE", new String[]                                  {"ASEC Create",                              "2", ""});
        put("android.permission.ASEC_DESTROY", new String[]                                 {"ASEC Destroy",                             "2", ""});
        put("android.permission.ASEC_MOUNT_UNMOUNT", new String[]                           {"Asec Mount Unmount",                       "2", ""});
        put("android.permission.ASEC_RENAME", new String[]                                  {"Asec Rename",                              "2", ""});
        put("android.permission.AUTHENTICATE_ACCOUNTS", new String[]                        {"Authenticate Accounts",                    "2", ""});
        put("android.permission.BACKUP", new String[]                                       {"Backup Device",                            "2", ""});
        put("android.permission.BATTERY_STATS", new String[]                                {"Battery Stats",                            "0", ""});
        put("android.permission.BIND_ACCESSIBILITY_SERVICE", new String[]                   {"Bind Accessibility Service",               "1", ""});
        put("android.permission.BIND_APPWIDGET", new String[]                               {"Bind AppWidget",                           "2", "Android/Apps"});
        put("android.permission.BIND_CARRIER_MESSAGING_SERVICE", new String[]               {"Bind Carrier Messaging Service",           "1", ""});
        put("android.permission.BIND_CARRIER_SERVICES", new String[]                        {"Bind Carrier Services",                    "1", ""});
        put("android.permission.BIND_CHOOSER_TARGET_SERVICE", new String[]                  {"Bind Chooser Target Service",              "1", ""});
        put("android.permission.BIND_CONDITION_PROVIDER_SERVICE", new String[]              {"Bind Condition Provider Service",          "1", ""});
        put("android.permission.BIND_CONNECTION_SERVICE", new String[]                      {"Connection Service",                       "1", ""});
        put("android.permission.BIND_DEVICE_ADMIN", new String[]                            {"Bind Device Admin",                        "1", ""});
        put("android.permission.BIND_DIRECTORY_SEARCH", new String[]                        {"Bind Directory Search",                    "1", ""});
        put("android.permission.BIND_DREAM_SERVICE", new String[]                           {"Bind Dream Service",                       "1", ""});
        put("android.permission.BIND_INCALL_SERVICE", new String[]                          {"Bind Incall Service",                      "1", ""});
        put("android.permission.BIND_INPUT_METHOD", new String[]                            {"Bind Input Method",                        "1", ""});
        put("android.permission.BIND_INTENT_FILTER_VERIFIER", new String[]                  {"Bind Intent Filter Verifier",              "1", ""});
        put("android.permission.BIND_JOB_SERVICE", new String[]                             {"Bind Job Service",                         "1", ""});
        put("android.permission.BIND_KEYGUARD_APPWIDGET", new String[]                      {"Bind Keyguard AppWidget",                  "1", ""});
        put("android.permission.BIND_MIDI_DEVICE_SERVICE", new String[]                     {"Bind MIDI Device Service",                 "1", ""});
        put("android.permission.BIND_NFC_SERVICE", new String[]                             {"Bind Nfc Service",                         "1", ""});
        put("android.permission.BIND_NOTIFICATION_LISTENER_SERVICE", new String[]           {"Bind Notification Listener Service",       "1", ""});
        put("android.permission.BIND_PACKAGE_VERIFIER", new String[]                        {"Bind Package Verifier",                    "1", ""});
        put("android.permission.BIND_PRINT_SERVICE", new String[]                           {"Bind Print Service",                       "1", ""});
        put("android.permission.BIND_PRINT_SPOOLER_SERVICE", new String[]                   {"Bind Print Spooler Service",               "1", ""});
        put("android.permission.BIND_REMOTE_DISPLAY", new String[]                          {"Bind Remote Display",                      "1", ""});
        put("android.permission.BIND_REMOTEVIEWS", new String[]                             {"Bind Remoteviews",                         "1", ""});
        put("android.permission.BIND_ROUTE_PROVIDER", new String[]                          {"Bind Route Provider",                      "1", ""});
        put("android.permission.BIND_TELECOM_CONNECTION_SERVICE", new String[]              {"Connect to Telecom Service",               "1", ""});
        put("android.permission.BIND_TEXT_SERVICE", new String[]                            {"Bind Text Service",                        "1", ""});
        put("android.permission.BIND_TRUST_AGENT", new String[]                             {"Bind Trust Agent",                         "1", ""});
        put("android.permission.BIND_TV_INPUT", new String[]                                {"Bind TV Input",                            "1", ""});
        put("android.permission.BIND_VOICE_INTERACTION", new String[]                       {"Bind Voice Interaction",                   "1", ""});
        put("android.permission.BIND_VPN_SERVICE", new String[]                             {"Bind VPN Service",                         "1", ""});
        put("android.permission.BIND_WALLPAPER", new String[]                               {"Wallpaper",                                "0", ""});
        put("android.permission.BLUETOOTH", new String[]                                    {"Bluetooth",                                "2", "Data Transmission"});
        put("android.permission.BLUETOOTH_ADMIN", new String[]                              {"Bluetooth Administration",                 "2", "Data Transmission"});
        put("android.permission.BLUETOOTH_MAP", new String[]                                {"Bluetooth Map",                            "2", "Data Transmission"});
        put("android.permission.BLUETOOTH_PRIVILEGED", new String[]                         {"Bluetooth Priviledged",                    "2", "Data Transmission"});
        put("android.permission.BLUETOOTH_STACK", new String[]                              {"Bluetooth Stack",                          "2", "Data Transmission"});
        put("android.permission.BRICK", new String[]                                        {"Brick the Device",                         "2", ""});
        put("android.permission.BROADCAST_CALLLOG_INFO", new String[]                       {"Broadcast Call Log Info",                  "2", ""});
        put("android.permission.BROADCAST_NETWORK_PRIVILEGED", new String[]                 {"Broadcast On Priviledged Network",         "2", ""});
        put("android.permission.BROADCAST_PACKAGE_REMOVED", new String[]                    {"Broadcast Package Removed",                "2", ""});
        put("android.permission.BROADCAST_PHONE_ACCOUNT_REGISTRATION", new String[]         {"Broadcast Phone Account Registration",     "2", ""});
        put("android.permission.BROADCAST_SMS", new String[]                                {"Send SMS",                                 "2", "Communication"});
        put("android.permission.BROADCAST_STICKY", new String[]                             {"Broadcast Sticky",                         "0", ""});
        put("android.permission.BROADCAST_WAP_PUSH", new String[]                           {"Broadcast WAP Push",                       "2", "Communication"});
        put("android.permission.CALL_PRIVILEGED", new String[]                              {"Call Any Number",                          "2", "Communication"});
        put("android.permission.CAMERA_DISABLE_TRANSMIT_LED", new String[]                  {"Camera Disable Transmit Led",              "0", ""});
        put("android.permission.CAMERA_SEND_SYSTEM_EVENTS", new String[]                    {"Camera Send System Events",                "0", ""});
        put("android.permission.CAPTURE_AUDIO_HOTWORD", new String[]                        {"Capture Audio Hotword",                    "2", ""});
        put("android.permission.CAPTURE_AUDIO_OUTPUT", new String[]                         {"Capture Audio Output",                     "2", ""});
        put("android.permission.CAMERA", new String[]                                       {"Camera",                                   "2", ""});
        put("android.permission.CAPTURE_SECURE_VIDEO_OUTPUT", new String[]                  {"Capture Secure Video Output",              "2", ""});
        put("android.permission.CAPTURE_TV_INPUT", new String[]                             {"Capture TV Input",                         "0", ""});
        put("android.permission.CAPTURE_VIDEO_OUTPUT", new String[]                         {"Capture Video Output",                     "2", ""});
        put("android.permission.CARRIER_FILTER_SMS", new String[]                           {"Carrier Filter SMS",                       "2", ""});
        put("android.permission.CHANGE_APP_IDLE_STATE", new String[]                        {"Change App Idle State",                    "1", ""});
        put("android.permission.CHANGE_BACKGROUND_DATA_SETTING", new String[]               {"Change Background Data Setting",           "0", ""});
        put("android.permission.CHANGE_COMPONENT_ENABLED_STATE", new String[]               {"Change Component Enabled State",           "2", ""});
        put("android.permission.CHANGE_CONFIGURATION", new String[]                         {"Change Configuration",                     "1", ""});
        put("android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST", new String[]            {"Change Device Idle Temp Whitelist",        "1", ""});
        put("android.permission.CHANGE_NETWORK_STATE", new String[]                         {"Configure Network",                        "2", "Data Transmission"});
        put("android.permission.CHANGE_WIFI_MULTICAST_STATE", new String[]                  {"Change WiFi Multicast",                    "2", "Data Transmission"});
        put("android.permission.CHANGE_WIFI_STATE", new String[]                            {"Change WiFi State",                        "2", "Data Transmission"});
        put("android.permission.CHANGE_WIMAX_STATE", new String[]                           {"Change Wimax State",                       "2", "Data Transmission"});
        put("android.permission.CLEAR_APP_CACHE", new String[]                              {"Clear App Cache",                          "0", ""});
        put("android.permission.CLEAR_APP_USER_DATA", new String[]                          {"Clear App User Data",                      "0", ""});
        put("android.permission.CONFIGURE_DISPLAY_COLOR_TRANSFORM", new String[]            {"Configure Display Color Transform",        "0", ""});
        put("android.permission.CONFIGURE_WIFI_DISPLAY", new String[]                       {"Configure Wifi",                           "2", "Data Transmission"});
        put("android.permission.CONFIRM_FULL_BACKUP", new String[]                          {"Confirm Full Backup",                      "1", ""});
        put("android.permission.CONNECTIVITY_INTERNAL", new String[]                        {"Connectivity Internal",                    "1", ""});
        put("android.permission.CONTROL_INCALL_EXPERIENCE", new String[]                    {"Control Incall Experience",                "1", ""});
        put("android.permission.CONTROL_KEYGUARD", new String[]                             {"Control Keyguard",                         "2", ""});
        put("android.permission.CONTROL_LOCATION_UPDATES", new String[]                     {"Control Location Updates",                 "2", "Location"});
        put("android.permission.CONTROL_VPN", new String[]                                  {"Control VPN",                              "2", ""});
        put("android.permission.CONTROL_WIFI_DISPLAY", new String[]                         {"Control WiFi Display",                     "1", ""});
        put("android.permission.COPY_PROTECTED_DATA", new String[]                          {"Copy Protected Data",                      "2", ""});
        put("android.permission.CRYPT_KEEPER", new String[]                                 {"Crypt Keeper",                             "2", ""});
        put("android.permission.DELETE_CACHE_FILES", new String[]                           {"Delete Cached Files",                      "0", ""});
        put("android.permission.DELETE_PACKAGES", new String[]                              {"Delete Packages",                          "2", ""});
        put("android.permission.DEVICE_POWER", new String[]                                 {"Control Device Power",                     "1", ""});
        put("android.permission.DIAGNOSTIC", new String[]                                   {"Diagnostics",                              "0", ""});
        put("android.permission.DISABLE_KEYGUARD", new String[]                             {"Display Keyguard",                         "1", ""});
        put("android.permission.DISPATCH_NFC_MESSAGE", new String[]                         {"Dispatch Nfc Message",                     "2", "Data Transmission"});
        put("android.permission.DOWNLOAD_CACHE_NON_PURGEABLE", new String[]                 {"Download Cache Non Purgeable",             "0", ""});
        put("android.permission.DUMP", new String[]                                         {"Dump",                                     "1", ""});
        put("android.permission.DVB_DEVICE", new String[]                                   {"Digital Video Broadcasting",               "1", ""});
        put("android.permission.EXPAND_STATUS_BAR", new String[]                            {"Expand Status Bar",                        "0", ""});
        put("android.permission.FACTORY_TEST", new String[]                                 {"Factory Test",                             "2", ""});
        put("android.permission.FILTER_EVENTS", new String[]                                {"Filter Events",                            "1", ""});
        put("android.permission.FLASHLIGHT", new String[]                                   {"Flashlight",                               "0", ""});
        put("android.permission.FORCE_BACK", new String[]                                   {"Force Back",                               "0", ""});
        put("android.permission.FORCE_STOP_PACKAGES", new String[]                          {"Force Stop Packages",                      "2", ""});
        put("android.permission.FRAME_STATS", new String[]                                  {"Frame Stats",                              "0", ""});
        put("android.permission.FREEZE_SCREEN", new String[]                                {"Freeze Screen",                            "1", ""});
        put("android.permission.GET_ACCOUNTS_PRIVILEGED", new String[]                      {"Get Privileged Accounts",                  "2", ""});
        put("android.permission.GET_ACCOUNTS", new String[]                                 {"User Accounts",                            "2", ""});
        put("android.permission.GET_APP_OPS_STATS", new String[]                            {"Get Application Operation Stats",          "1", ""});
        put("android.permission.GET_DETAILED_TASKS", new String[]                           {"Get Detailed Tasks",                       "1", ""});
        put("android.permission.GET_PACKAGE_IMPORTANCE", new String[]                       {"Get Package Importance",                   "1", ""});
        put("android.permission.GET_PACKAGE_SIZE", new String[]                             {"Get Package Size",                         "2", "Android/Apps"});
        put("android.permission.GET_TASKS", new String[]                                    {"Get Tasks List",                           "2", ""});
        put("android.permission.GET_TOP_ACTIVITY_INFO", new String[]                        {"Get Top Activities Information",           "2", ""});
        put("android.permission.GLOBAL_SEARCH", new String[]                                {"Global Search",                            "2", "Android/Apps"});
        put("android.permission.GLOBAL_SEARCH_CONTROL", new String[]                        {"Global Search Control",                    "1", ""});
        put("android.permission.GRANT_RUNTIME_PERMISSIONS", new String[]                    {"Grant Runtime Permissions",                "2", ""});
        put("android.permission.HARDWARE_TEST", new String[]                                {"Hardware Test",                            "1", ""});
        put("android.permission.HDMI_CEC", new String[]                                     {"Hdmi Cec",                                 "1", ""});
        put("android.permission.INJECT_EVENTS", new String[]                                {"Inject Events",                            "2", ""});
        put("android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS", new String[]            {"Install Grant Runtime Permissions",        "2", ""});
        put("android.permission.INSTALL_LOCATION_PROVIDER", new String[]                    {"Install Location Provider",                "2", "Location"});
        put("android.permission.INSTALL_PACKAGES", new String[]                             {"Install Packages",                         "2", "Android/Apps"});
        put("android.permission.INTENT_FILTER_VERIFICATION_AGENT", new String[]             {"Intent Filter Verification",               "2", ""});
        put("android.permission.INTERACT_ACROSS_USERS", new String[]                        {"Interact Across Users",                    "2", ""});
        put("android.permission.INTERACT_ACROSS_USERS_FULL", new String[]                   {"Interact Across Users",                    "2", ""});
        put("android.permission.INTERNAL_SYSTEM_WINDOW", new String[]                       {"Create Internal Popups",                   "2", ""});
        put("android.permission.INTERNET", new String[]                                     {"Access Internet",                          "1", ""});
        put("android.permission.INVOKE_CARRIER_SETUP", new String[]                         {"Invoke Carrier Setup",                     "1", ""});
        put("android.permission.KILL_BACKGROUND_PROCESSES", new String[]                    {"Kill Background Processes",                "2", "Android/Apps"});
        put("android.permission.KILL_UID", new String[]                                     {"Kill UID",                                 "2", ""});
        put("android.permission.LAUNCH_TRUST_AGENT_SETTINGS", new String[]                  {"Launch Trust Agent Settings",              "1", ""});
        put("android.permission.LOCAL_MAC_ADDRESS", new String[]                            {"Local Mac Address",                        "2", ""});
        put("android.permission.LOCATION_HARDWARE", new String[]                            {"Location Hardware",                        "2", "Location"});
        put("android.permission.LOOP_RADIO", new String[]                                   {"Loop Radio",                               "0", ""});
        put("android.permission.MANAGE_ACCOUNTS", new String[]                              {"Manage Accounts",                          "2", ""});
        put("android.permission.MANAGE_ACTIVITY_STACKS", new String[]                       {"Manage Activity Stacks",                   "1", ""});
        put("android.permission.MANAGE_APP_TOKENS", new String[]                            {"Manage App Tokens",                        "2", ""});
        put("android.permission.MANAGE_CA_CERTIFICATES", new String[]                       {"Manage Ca Certificates",                   "2", ""});
        put("android.permission.MANAGE_DEVICE_ADMINS", new String[]                         {"Manage Device Admins",                     "2", ""});
        put("android.permission.MANAGE_DOCUMENTS", new String[]                             {"Manage Documents",                         "2", "Android/Apps"});
        put("android.permission.MANAGE_FINGERPRINT", new String[]                           {"Manage Fingerprint",                       "2", ""});
        put("android.permission.MANAGE_MEDIA_PROJECTION", new String[]                      {"Manage Media Projection",                  "2", ""});
        put("android.permission.MANAGE_NETWORK_POLICY", new String[]                        {"Manage Network Policy",                    "2", "Data Transmission"});
        put("android.permission.MANAGE_PROFILE_AND_DEVICE_OWNERS", new String[]             {"Manage Profile and Device Owners",         "2", ""});
        put("android.permission.MANAGE_USB", new String[]                                   {"Manage USB",                               "2", ""});
        put("android.permission.MANAGE_USERS", new String[]                                 {"Manage Users",                             "2", ""});
        put("android.permission.MANAGE_VOICE_KEYPHRASES", new String[]                      {"Manage Voice Keyphrases",                  "2", ""});
        put("android.permission.MASTER_CLEAR", new String[]                                 {"Master Clear",                             "2", ""});
        put("android.permission.MEDIA_CONTENT_CONTROL", new String[]                        {"Media Content Control",                    "1", ""});
        put("android.permission.MODIFY_APPWIDGET_BIND_PERMISSIONS", new String[]            {"Modify Appwidget Bind Permissions",        "2", ""});
        put("android.permission.MODIFY_AUDIO_ROUTING", new String[]                         {"Modify Audio Routing",                     "2", ""});
        put("android.permission.MODIFY_AUDIO_SETTINGS", new String[]                        {"Modify Audio Settings",                    "1", ""});
        put("android.permission.MODIFY_NETWORK_ACCOUNTING", new String[]                    {"Modify Network Accounting",                "1", ""});
        put("android.permission.MODIFY_PARENTAL_CONTROLS", new String[]                     {"Modify Parental Controls",                 "2", ""});
        put("android.permission.MODIFY_PHONE_STATE", new String[]                           {"Modify Phone State",                       "2", "Communication"});
        put("android.permission.MOUNT_FORMAT_FILESYSTEMS", new String[]                     {"Mount Format Filesystems",                 "2", ""});
        put("android.permission.MOUNT_UNMOUNT_FILESYSTEMS", new String[]                    {"Mount and Unmount Filesystems",            "2", ""});
        put("android.permission.MOVE_PACKAGE", new String[]                                 {"Move Package",                             "2", ""});
        put("android.permission.NET_ADMIN", new String[]                                    {"Network Admin",                            "2", ""});
        put("android.permission.NET_TUNNELING", new String[]                                {"Net Tunneling",                            "2", ""});
        put("android.permission.NFC", new String[]                                          {"NFC",                                      "2", "Data Transmission"});
        put("android.permission.NFC_HANDOVER_STATUS", new String[]                          {"NFS Handover Status",                      "2", ""});
        put("android.permission.NOTIFY_PENDING_SYSTEM_UPDATE", new String[]                 {"Notify Pending System Update",             "2", ""});
        put("android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS", new String[]             {"Observe Grant Revoke Permissions",         "2", ""});
        put("android.permission.OEM_UNLOCK_STATE", new String[]                             {"Oem Unlock State",                         "1", ""});
        put("android.permission.OVERRIDE_WIFI_CONFIG", new String[]                         {"Override Wifi Config",                     "2", "Data Transmission"});
        put("android.permission.PACKAGE_PRIVACY_VERIFICATION_AGENT", new String[]           {"Package Privacy Verification Agent",       "2", ""});
        put("android.permission.PACKAGE_USAGE_STATS", new String[]                          {"Package Usage Stats",                      "2", ""});
        put("android.permission.PACKAGE_VERIFICATION_AGENT", new String[]                   {"Package Verification Agent",               "2", ""});
        put("android.permission.PACKET_KEEPALIVE_OFFLOAD", new String[]                     {"Packet Keepalive Offload",                 "1", ""});
        put("android.permission.PEERS_MAC_ADDRESS", new String[]                            {"Get WiFi Mac Address",                     "2", "Data Transmission"});
        put("android.permission.PERFORM_CDMA_PROVISIONING", new String[]                    {"Perform CDMA Provisioning",                "2", "Data Transmission"});
        put("android.permission.PERFORM_SIM_ACTIVATION", new String[]                       {"Activate Sim",                             "2", ""});
        put("android.permission.PERSISTENT_ACTIVITY", new String[]                          {"Persistent Activity",                      "1", ""});
        put("android.permission.POLICY_MANAGER_SERVICE", new String[]                       {"Policy Manager Service",                   "2", ""});
        put("android.permission.PROCESS_CALLLOG_INFO", new String[]                         {"Process Call log Info",                    "2", ""});
        put("android.permission.PROCESS_PHONE_ACCOUNT_REGISTRATION", new String[]           {"Phone Account Registration",               "2", ""});
        put("android.permission.PROVIDE_TRUST_AGENT", new String[]                          {"Provide Trust Agent",                      "2", ""});
        put("android.permission.QUERY_DO_NOT_ASK_CREDENTIALS_ON_BOOT", new String[]         {"Query Do Not Ask Credentials On Boot",     "1", ""});
        put("android.permission.READ_DREAM_STATE", new String[]                             {"Read Dream State",                         "0", ""});
        put("android.permission.READ_FRAME_BUFFER", new String[]                            {"Read Frame Buffer",                        "0", ""});
        put("android.permission.READ_INPUT_STATE", new String[]                             {"Read Input State",                         "2", ""});
        put("android.permission.READ_INSTALL_SESSIONS", new String[]                        {"Read Install Sessions",                    "2", ""});
        put("android.permission.READ_LOGS", new String[]                                    {"Read Logs",                                "2", "Android/Apps"});
        put("android.permission.READ_NETWORK_USAGE_HISTORY", new String[]                   {"Read Network Usage History",               "2", ""});
        put("android.permission.READ_PRECISE_PHONE_STATE", new String[]                     {"Read Precise Phone State",                 "2", ""});
        put("android.permission.READ_PRIVILEGED_PHONE_STATE", new String[]                  {"Read Priviledged Phone State",             "2", ""});
        put("android.permission.READ_PROFILE", new String[]                                 {"Read Person Profile Data",                 "2", ""});
        put("android.permission.READ_SEARCH_INDEXABLES", new String[]                       {"Read Search Indexable",                    "2", ""});
        put("android.permission.READ_SOCIAL_STREAM", new String[]                           {"Read Social Stream",                       "2", ""});
        put("android.permission.READ_SYNC_SETTINGS", new String[]                           {"Read Sync Settings",                       "2", ""});
        put("android.permission.READ_SYNC_STATS", new String[]                              {"Read Sync Stats",                          "2", ""});
        put("android.permission.READ_USER_DICTIONARY", new String[]                         {"Read User Dictionary",                     "2", ""});
        put("android.permission.READ_WIFI_CREDENTIAL", new String[]                         {"Read WiFi Credentials",                    "2", ""});
        put("android.permission.READ_CONTACTS", new String[]                                {"Read Contacts",                            "2", ""});
        put("android.permission.READ_EXTERNAL_STORAGE", new String[]                        {"Read External Storage",                    "2", "Storage/Filesystem"});
        put("android.permission.READ_PHONE_STATE", new String[]                             {"Read Phone State",                         "2", "Communication"});
        put("android.permission.READ_SMS", new String[]                                     {"Read SMS",                                 "2", "Communication"});
        put("android.permission.REAL_GET_TASKS", new String[]                               {"Get Tasks",                                "1", ""});
        put("android.permission.REBOOT", new String[]                                       {"Reboot",                                   "0", ""});
        put("android.permission.RECEIVE_BLUETOOTH_MAP", new String[]                        {"Receive Bluetooth Map Info",               "1", ""});
        put("android.permission.RECEIVE_BOOT_COMPLETED", new String[]                       {"Receive Boot Event",                       "1", ""});
        put("android.permission.RECEIVE_DATA_ACTIVITY_CHANGE", new String[]                 {"Receive Data Activity Change",             "1", ""});
        put("android.permission.RECEIVE_EMERGENCY_BROADCAST", new String[]                  {"Receive Emergency Broadcast",              "1", ""});
        put("android.permission.RECEIVE_STK_COMMANDS", new String[]                         {"Receive STK Commands",                     "1", ""});
        put("android.permission.RECEIVE_WIFI_CREDENTIAL_CHANGE", new String[]               {"Receive WiFi Credential Change",           "1", ""});
        put("android.permission.RECEIVE_MMS", new String[]                                  {"Receive MMS",                              "2", "Communication"});
        put("android.permission.RECEIVE_SMS", new String[]                                  {"Receive SMS",                              "2", "Communication"});
        put("android.permission.RECORD_AUDIO", new String[]                                 {"Microphone",                             "2", ""});
        put("android.permission.RECOVERY", new String[]                                     {"Recovery",                                 "1", ""});
        put("android.permission.REGISTER_CALL_PROVIDER", new String[]                       {"Register Call Provider",                   "2", ""});
        put("android.permission.REGISTER_CONNECTION_MANAGER", new String[]                  {"Register Connection Manager",              "2", ""});
        put("android.permission.REGISTER_SIM_SUBSCRIPTION", new String[]                    {"Register Sim Subscription",                "2", ""});
        put("android.permission.REMOTE_AUDIO_PLAYBACK", new String[]                        {"Remote Audio Feedback",                    "1", ""});
        put("android.permission.REMOVE_DRM_CERTIFICATES", new String[]                      {"Remove Drm Certificates",                  "1", ""});
        put("android.permission.REMOVE_TASKS", new String[]                                 {"Remove Tasks",                             "1", ""});
        put("android.permission.REORDER_TASKS", new String[]                                {"Reorder Running Tasks",                    "2", ""});
        put("android.permission.REPORT_SUPERUSER", new String[]                             {"Report SuperUser",                         "2", ""});
        put("android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", new String[]         {"Request Ignore Battery Optimizations",     "1", ""});
        put("android.permission.REQUEST_INSTALL_PACKAGES", new String[]                     {"Request Install Packages",                 "1", ""});
        put("android.permission.REQUEST_SUPERUSER", new String[]                            {"Request Superuser Priviledges",            "2", ""});
        put("android.permission.RESET_FINGERPRINT_LOCKOUT", new String[]                    {"Reset Fingerprint Lockout",                "2", ""});
        put("android.permission.RESTART_PACKAGES", new String[]                             {"Restart Packages",                         "2", ""});
        put("android.permission.RETRIEVE_WINDOW_CONTENT", new String[]                      {"Retrieve Window Content",                  "2", ""});
        put("android.permission.RETRIEVE_WINDOW_TOKEN", new String[]                        {"Retrieve Window Token",                    "2", ""});
        put("android.permission.REVOKE_RUNTIME_PERMISSIONS", new String[]                   {"Revoke Runtime Permissions",               "2", ""});
        put("android.permission.SCORE_NETWORKS", new String[]                               {"Score Networks",                           "1", ""});
        put("android.permission.SEND_CALL_LOG_CHANGE", new String[]                         {"Send Call Log Change",                     "2", ""});
        put("android.permission.SEND_DOWNLOAD_COMPLETED_INTENTS", new String[]              {"Send Download Complete Intents",           "2", ""});
        put("android.permission.SEND_RESPOND_VIA_MESSAGE", new String[]                     {"Send Response via Message",                "2", "Communication"});
        put("android.permission.SEND_SMS", new String[]                                     {"Send SMS",                                 "2", "Communication"});
        put("android.permission.SERIAL_PORT", new String[]                                  {"Access Serial Port",                       "2", ""});
        put("android.permission.SET_ACTIVITY_WATCHER", new String[]                         {"Set Activiy Watcher",                      "2", ""});
        put("android.permission.SET_ALWAYS_FINISH", new String[]                            {"Set Always Finish",                        "2", ""});
        put("android.permission.SET_ANIMATION_SCALE", new String[]                          {"Set Animation Scaling",                    "2", ""});
        put("android.permission.SET_DEBUG_APP", new String[]                                {"Set Debug App",                            "2", ""});
        put("android.permission.SET_INPUT_CALIBRATION", new String[]                        {"Calibrate Input",                          "2", ""});
        put("android.permission.SET_KEYBOARD_LAYOUT", new String[]                          {"Set Keyboard Layout",                      "0", ""});
        put("android.permission.SET_ORIENTATION", new String[]                              {"Set Orientation",                          "2", ""});
        put("android.permission.SET_POINTER_SPEED", new String[]                            {"Set Pointer Speed",                        "2", ""});
        put("android.permission.SET_PREFERRED_APPLICATIONS", new String[]                   {"Set Preferred Applications",               "2", ""});
        put("android.permission.SET_PROCESS_LIMIT", new String[]                            {"Set Process Limits",                       "2", ""});
        put("android.permission.SET_SCREEN_COMPATIBILITY", new String[]                     {"Set Screen Compatibility",                 "2", ""});
        put("android.permission.SET_TIME", new String[]                                     {"Set Time",                                 "2", ""});
        put("android.permission.SET_TIME_ZONE", new String[]                                {"Set Time Zone",                            "2", ""});
        put("android.permission.SET_WALLPAPER", new String[]                                {"Set Wallpaper",                            "0", ""});
        put("android.permission.SET_WALLPAPER_COMPONENT", new String[]                      {"Set Wallpaper",                            "0", ""});
        put("android.permission.SET_WALLPAPER_HINTS", new String[]                          {"Set Wallpaper Hints",                      "1", ""});
        put("android.permission.SHUTDOWN", new String[]                                     {"Shutdown Phone",                           "1", ""});
        put("android.permission.SIGNAL_PERSISTENT_PROCESSES", new String[]                  {"Signal Persistent Processes",              "1", ""});
        put("android.permission.START_ANY_ACTIVITY", new String[]                           {"Start Activities",                         "1", ""});
        put("android.permission.START_PRINT_SERVICE_CONFIG_ACTIVITY", new String[]          {"Start Print Service Config Activity",      "1", ""});
        put("android.permission.START_TASKS_FROM_RECENTS", new String[]                     {"Start Tasks From Recents",                 "1", ""});
        put("android.permission.STATUS_BAR", new String[]                                   {"Status Bar",                               "2", ""});
        put("android.permission.STATUS_BAR_SERVICE", new String[]                           {"Status Bar Service",                       "2", ""});
        put("android.permission.STOP_APP_SWITCHES", new String[]                            {"Stop App Switches",                        "2", ""});
        put("android.permission.SUBSCRIBED_FEEDS_READ", new String[]                        {"Read Subscribed Feeds",                    "2", ""});
        put("android.permission.SUBSCRIBED_FEEDS_WRITE", new String[]                       {"Write Subscribed Feeds",                   "2", ""});
        put("android.permission.SYSTEM_ALERT_WINDOW", new String[]                          {"System Alert Window",                      "1", ""});
        put("android.permission.TABLET_MODE", new String[]                                  {"Tablet Mode",                              "1", ""});
        put("android.permission.TEMPORARY_ENABLE_ACCESSIBILITY", new String[]               {"Temporarily Enable Accessibility Options", "2", ""});
        put("android.permission.TRANSMIT_IR", new String[]                                  {"Transmit IR",                              "2", ""});
        put("android.permission.TRUST_LISTENER", new String[]                               {"Trust Listener",                           "2", "Data Transmission"});
        put("android.permission.TV_INPUT_HARDWARE", new String[]                            {"TV Input Hardware",                        "1", ""});
        put("android.permission.UPDATE_APP_OPS_STATS", new String[]                         {"Update App Ops Stats",                     "2", ""});
        put("android.permission.UPDATE_CONFIG", new String[]                                {"Update Config",                            "2", ""});
        put("android.permission.UPDATE_DEVICE_STATS", new String[]                          {"Update Device Stats",                      "2", ""});
        put("android.permission.UPDATE_LOCK", new String[]                                  {"Update Lock",                              "2", ""});
        put("android.permission.USE_CREDENTIALS", new String[]                              {"Use Account Credentials",                  "2", ""});
        put("android.permission.USER_ACTIVITY", new String[]                                {"User Activity",                            "1", ""});
        put("android.permission.VIBRATE", new String[]                                      {"Vibrate",                                  "0", ""});
        put("android.permission.WAKE_LOCK", new String[]                                    {"Wake Lock",                                "1", ""});
        put("android.permission.WRITE_APN_SETTINGS", new String[]                           {"Write APN Settings",                       "2", ""});
        put("android.permission.WRITE_DREAM_STATE", new String[]                            {"Write Dream State",                        "2", ""});
        put("android.permission.WRITE_GSERVICES", new String[]                              {"Write G-Services",                         "2", ""});
        put("android.permission.WRITE_MEDIA_STORAGE", new String[]                          {"Write Media Storage",                      "2", ""});
        put("android.permission.WRITE_PROFILE", new String[]                                {"Write Profile",                            "2", ""});
        put("android.permission.WRITE_SECURE_SETTINGS", new String[]                        {"Write Secure Settings",                    "2", ""});
        put("android.permission.WRITE_SETTINGS", new String[]                               {"Write Settings",                           "2", ""});
        put("android.permission.WRITE_SMS", new String[]                                    {"Write SMS",                                "2", ""});
        put("android.permission.WRITE_SOCIAL_STREAM", new String[]                          {"Write Social Stream",                      "2", ""});
        put("android.permission.WRITE_SYNC_SETTINGS", new String[]                          {"Write Sync Settings",                      "2", ""});
        put("android.permission.WRITE_USER_DICTIONARY", new String[]                        {"Write User Dictionary",                    "2", ""});
        put("android.permission.WRITE_CONTACTS", new String[]                               {"Write Contacts",                           "2", ""});
        put("android.permission.WRITE_EXTERNAL_STORAGE", new String[]                       {"Write External Storage",                   "2", "Storage/Filesystem"});
        put("com.android.alarm.permission.SET_ALARM", new String[]                          {"Set Alarm",                                "0", ""});
        put("com.android.browser.permission.PRELOAD", new String[]                          {"Browser Preload",                          "1", ""});
        put("com.android.browser.permission.READ_HISTORY_BOOKMARKS", new String[]           {"Read History Bookmarks",                   "2", ""});
        put("com.android.browser.perMission.write_history_bookmarks", new String[]          {"write History Bookmarks",                  "2", ""});
        put("com.android.certinstaller.INSTall_as_user", new String[]                       {"Install As User",                          "2", ""});
        put("com.android.email.perMission.access_provider", new String[]                    {"Email Access Provider",                    "2", ""});
        put("com.android.launcher.perMission.install_shortcut", new String[]                {"install Shortcut",                         "2", ""});
        put("com.android.launcher.permission.UNINSTALL_SHORTCUT", new String[]              {"Uninstall Shortcuts",                      "2", ""});
        put("com.android.launcher3.perMission.receive_first_load_broadcast", new String[]   {"receive First Load Broadcast",             "2", ""});
        put("com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS", new String[]      {"Receive Launch Broadcasts",                "2", ""});
        put("com.android.printspooler.permission.ACCESS_ALL_PRINT_JOBS", new String[]       {"Access Print Jobs",                        "2", ""});
        put("com.android.systemui.perMission.self", new String[]                            {"self",                                     "1", ""});
        put("com.android.voicemail.permission.READ_VOICEMAIL", new String[]                 {"Read Voicemail",                           "2", ""});
        put("com.android.voicemail.perMission.write_voicemail", new String[]                {"write Voicemail",                          "2", ""});
    }};
}